<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kota = [
            ['id'=>1101,'kota'=>'KABUPATEN SIMEULUE','id_provinsi'=>11],
            ['id'=>1102,'kota'=>'KABUPATEN ACEH SINGKIL','id_provinsi'=>11],
            ['id'=>1103,'kota'=>'KABUPATEN ACEH SELATAN','id_provinsi'=>11],
            ['id'=>1104,'kota'=>'KABUPATEN ACEH TENGGARA','id_provinsi'=>11],
            ['id'=>1105,'kota'=>'KABUPATEN ACEH TIMUR','id_provinsi'=>11],
            ['id'=>1106,'kota'=>'KABUPATEN ACEH TENGAH','id_provinsi'=>11],
            ['id'=>1107,'kota'=>'KABUPATEN ACEH BARAT','id_provinsi'=>11],
            ['id'=>1108,'kota'=>'KABUPATEN ACEH BESAR','id_provinsi'=>11],
            ['id'=>1109,'kota'=>'KABUPATEN PIDIE','id_provinsi'=>11],
            ['id'=>1110,'kota'=>'KABUPATEN BIREUEN','id_provinsi'=>11],
            ['id'=>1111,'kota'=>'KABUPATEN ACEH UTARA','id_provinsi'=>11],
            ['id'=>1112,'kota'=>'KABUPATEN ACEH BARAT DAYA','id_provinsi'=>11],
            ['id'=>1113,'kota'=>'KABUPATEN GAYO LUES','id_provinsi'=>11],
            ['id'=>1114,'kota'=>'KABUPATEN ACEH TAMIANG','id_provinsi'=>11],
            ['id'=>1115,'kota'=>'KABUPATEN NAGAN RAYA','id_provinsi'=>11],
            ['id'=>1116,'kota'=>'KABUPATEN ACEH JAYA','id_provinsi'=>11],
            ['id'=>1117,'kota'=>'KABUPATEN BENER MERIAH','id_provinsi'=>11],
            ['id'=>1118,'kota'=>'KABUPATEN PIDIE JAYA','id_provinsi'=>11],
            ['id'=>1171,'kota'=>'KOTA BANDA ACEH','id_provinsi'=>11],
            ['id'=>1172,'kota'=>'KOTA SABANG','id_provinsi'=>11],
            ['id'=>1173,'kota'=>'KOTA LANGSA','id_provinsi'=>11],
            ['id'=>1174,'kota'=>'KOTA LHOKSEUMAWE','id_provinsi'=>11],
            ['id'=>1175,'kota'=>'KOTA SUBULUSSALAM','id_provinsi'=>11],
            ['id'=>1201,'kota'=>'KABUPATEN NIAS','id_provinsi'=>12],
            ['id'=>1202,'kota'=>'KABUPATEN MANDAILING NATAL','id_provinsi'=>12],
            ['id'=>1203,'kota'=>'KABUPATEN TAPANULI SELATAN','id_provinsi'=>12],
            ['id'=>1204,'kota'=>'KABUPATEN TAPANULI TENGAH','id_provinsi'=>12],
            ['id'=>1205,'kota'=>'KABUPATEN TAPANULI UTARA','id_provinsi'=>12],
            ['id'=>1206,'kota'=>'KABUPATEN TOBA SAMOSIR','id_provinsi'=>12],
            ['id'=>1207,'kota'=>'KABUPATEN LABUHAN BATU','id_provinsi'=>12],
            ['id'=>1208,'kota'=>'KABUPATEN ASAHAN','id_provinsi'=>12],
            ['id'=>1209,'kota'=>'KABUPATEN SIMALUNGUN','id_provinsi'=>12],
            ['id'=>1210,'kota'=>'KABUPATEN DAIRI','id_provinsi'=>12],
            ['id'=>1211,'kota'=>'KABUPATEN KARO','id_provinsi'=>12],
            ['id'=>1212,'kota'=>'KABUPATEN DELI SERDANG','id_provinsi'=>12],
            ['id'=>1213,'kota'=>'KABUPATEN LANGKAT','id_provinsi'=>12],
            ['id'=>1214,'kota'=>'KABUPATEN NIAS SELATAN','id_provinsi'=>12],
            ['id'=>1215,'kota'=>'KABUPATEN HUMBANG HASUNDUTAN','id_provinsi'=>12],
            ['id'=>1216,'kota'=>'KABUPATEN PAKPAK BHARAT','id_provinsi'=>12],
            ['id'=>1217,'kota'=>'KABUPATEN SAMOSIR','id_provinsi'=>12],
            ['id'=>1218,'kota'=>'KABUPATEN SERDANG BEDAGAI','id_provinsi'=>12],
            ['id'=>1219,'kota'=>'KABUPATEN BATU BARA','id_provinsi'=>12],
            ['id'=>1220,'kota'=>'KABUPATEN PADANG LAWAS UTARA','id_provinsi'=>12],
            ['id'=>1221,'kota'=>'KABUPATEN PADANG LAWAS','id_provinsi'=>12],
            ['id'=>1222,'kota'=>'KABUPATEN LABUHAN BATU SELATAN','id_provinsi'=>12],
            ['id'=>1223,'kota'=>'KABUPATEN LABUHAN BATU UTARA','id_provinsi'=>12],
            ['id'=>1224,'kota'=>'KABUPATEN NIAS UTARA','id_provinsi'=>12],
            ['id'=>1225,'kota'=>'KABUPATEN NIAS BARAT','id_provinsi'=>12],
            ['id'=>1271,'kota'=>'KOTA SIBOLGA','id_provinsi'=>12],
            ['id'=>1272,'kota'=>'KOTA TANJUNG BALAI','id_provinsi'=>12],
            ['id'=>1273,'kota'=>'KOTA PEMATANG SIANTAR','id_provinsi'=>12],
            ['id'=>1274,'kota'=>'KOTA TEBING TINGGI','id_provinsi'=>12],
            ['id'=>1275,'kota'=>'KOTA MEDAN','id_provinsi'=>12],
            ['id'=>1276,'kota'=>'KOTA BINJAI','id_provinsi'=>12],
            ['id'=>1277,'kota'=>'KOTA PADANGSIDIMPUAN','id_provinsi'=>12],
            ['id'=>1278,'kota'=>'KOTA GUNUNGSITOLI','id_provinsi'=>12],
            ['id'=>1301,'kota'=>'KABUPATEN KEPULAUAN MENTAWAI','id_provinsi'=>13],
            ['id'=>1302,'kota'=>'KABUPATEN PESISIR SELATAN','id_provinsi'=>13],
            ['id'=>1303,'kota'=>'KABUPATEN SOLOK','id_provinsi'=>13],
            ['id'=>1304,'kota'=>'KABUPATEN SIJUNJUNG','id_provinsi'=>13],
            ['id'=>1305,'kota'=>'KABUPATEN TANAH DATAR','id_provinsi'=>13],
            ['id'=>1306,'kota'=>'KABUPATEN PADANG PARIAMAN','id_provinsi'=>13],
            ['id'=>1307,'kota'=>'KABUPATEN AGAM','id_provinsi'=>13],
            ['id'=>1308,'kota'=>'KABUPATEN LIMA PULUH KOTA','id_provinsi'=>13],
            ['id'=>1309,'kota'=>'KABUPATEN PASAMAN','id_provinsi'=>13],
            ['id'=>1310,'kota'=>'KABUPATEN SOLOK SELATAN','id_provinsi'=>13],
            ['id'=>1311,'kota'=>'KABUPATEN DHARMASRAYA','id_provinsi'=>13],
            ['id'=>1312,'kota'=>'KABUPATEN PASAMAN BARAT','id_provinsi'=>13],
            ['id'=>1371,'kota'=>'KOTA PADANG','id_provinsi'=>13],
            ['id'=>1372,'kota'=>'KOTA SOLOK','id_provinsi'=>13],
            ['id'=>1373,'kota'=>'KOTA SAWAH LUNTO','id_provinsi'=>13],
            ['id'=>1374,'kota'=>'KOTA PADANG PANJANG','id_provinsi'=>13],
            ['id'=>1375,'kota'=>'KOTA BUKITTINGGI','id_provinsi'=>13],
            ['id'=>1376,'kota'=>'KOTA PAYAKUMBUH','id_provinsi'=>13],
            ['id'=>1377,'kota'=>'KOTA PARIAMAN','id_provinsi'=>13],
            ['id'=>1401,'kota'=>'KABUPATEN KUANTAN SINGINGI','id_provinsi'=>14],
            ['id'=>1402,'kota'=>'KABUPATEN INDRAGIRI HULU','id_provinsi'=>14],
            ['id'=>1403,'kota'=>'KABUPATEN INDRAGIRI HILIR','id_provinsi'=>14],
            ['id'=>1404,'kota'=>'KABUPATEN PELALAWAN','id_provinsi'=>14],
            ['id'=>1405,'kota'=>'KABUPATEN S I A K','id_provinsi'=>14],
            ['id'=>1406,'kota'=>'KABUPATEN KAMPAR','id_provinsi'=>14],
            ['id'=>1407,'kota'=>'KABUPATEN ROKAN HULU','id_provinsi'=>14],
            ['id'=>1408,'kota'=>'KABUPATEN BENGKALIS','id_provinsi'=>14],
            ['id'=>1409,'kota'=>'KABUPATEN ROKAN HILIR','id_provinsi'=>14],
            ['id'=>1410,'kota'=>'KABUPATEN KEPULAUAN MERANTI','id_provinsi'=>14],
            ['id'=>1471,'kota'=>'KOTA PEKANBARU','id_provinsi'=>14],
            ['id'=>1473,'kota'=>'KOTA D U M A I','id_provinsi'=>14],
            ['id'=>1501,'kota'=>'KABUPATEN KERINCI','id_provinsi'=>15],
            ['id'=>1502,'kota'=>'KABUPATEN MERANGIN','id_provinsi'=>15],
            ['id'=>1503,'kota'=>'KABUPATEN SAROLANGUN','id_provinsi'=>15],
            ['id'=>1504,'kota'=>'KABUPATEN BATANG HARI','id_provinsi'=>15],
            ['id'=>1505,'kota'=>'KABUPATEN MUARO JAMBI','id_provinsi'=>15],
            ['id'=>1506,'kota'=>'KABUPATEN TANJUNG JABUNG TIMUR','id_provinsi'=>15],
            ['id'=>1507,'kota'=>'KABUPATEN TANJUNG JABUNG BARAT','id_provinsi'=>15],
            ['id'=>1508,'kota'=>'KABUPATEN TEBO','id_provinsi'=>15],
            ['id'=>1509,'kota'=>'KABUPATEN BUNGO','id_provinsi'=>15],
            ['id'=>1571,'kota'=>'KOTA JAMBI','id_provinsi'=>15],
            ['id'=>1572,'kota'=>'KOTA SUNGAI PENUH','id_provinsi'=>15],
            ['id'=>1601,'kota'=>'KABUPATEN OGAN KOMERING ULU','id_provinsi'=>16],
            ['id'=>1602,'kota'=>'KABUPATEN OGAN KOMERING ILIR','id_provinsi'=>16],
            ['id'=>1603,'kota'=>'KABUPATEN MUARA ENIM','id_provinsi'=>16],
            ['id'=>1604,'kota'=>'KABUPATEN LAHAT','id_provinsi'=>16],
            ['id'=>1605,'kota'=>'KABUPATEN MUSI RAWAS','id_provinsi'=>16],
            ['id'=>1606,'kota'=>'KABUPATEN MUSI BANYUASIN','id_provinsi'=>16],
            ['id'=>1607,'kota'=>'KABUPATEN BANYU ASIN','id_provinsi'=>16],
            ['id'=>1608,'kota'=>'KABUPATEN OGAN KOMERING ULU SELATAN','id_provinsi'=>16],
            ['id'=>1609,'kota'=>'KABUPATEN OGAN KOMERING ULU TIMUR','id_provinsi'=>16],
            ['id'=>1610,'kota'=>'KABUPATEN OGAN ILIR','id_provinsi'=>16],
            ['id'=>1611,'kota'=>'KABUPATEN EMPAT LAWANG','id_provinsi'=>16],
            ['id'=>1612,'kota'=>'KABUPATEN PENUKAL ABAB LEMATANG ILIR','id_provinsi'=>16],
            ['id'=>1613,'kota'=>'KABUPATEN MUSI RAWAS UTARA','id_provinsi'=>16],
            ['id'=>1671,'kota'=>'KOTA PALEMBANG','id_provinsi'=>16],
            ['id'=>1672,'kota'=>'KOTA PRABUMULIH','id_provinsi'=>16],
            ['id'=>1673,'kota'=>'KOTA PAGAR ALAM','id_provinsi'=>16],
            ['id'=>1674,'kota'=>'KOTA LUBUKLINGGAU','id_provinsi'=>16],
            ['id'=>1701,'kota'=>'KABUPATEN BENGKULU SELATAN','id_provinsi'=>17],
            ['id'=>1702,'kota'=>'KABUPATEN REJANG LEBONG','id_provinsi'=>17],
            ['id'=>1703,'kota'=>'KABUPATEN BENGKULU UTARA','id_provinsi'=>17],
            ['id'=>1704,'kota'=>'KABUPATEN KAUR','id_provinsi'=>17],
            ['id'=>1705,'kota'=>'KABUPATEN SELUMA','id_provinsi'=>17],
            ['id'=>1706,'kota'=>'KABUPATEN MUKOMUKO','id_provinsi'=>17],
            ['id'=>1707,'kota'=>'KABUPATEN LEBONG','id_provinsi'=>17],
            ['id'=>1708,'kota'=>'KABUPATEN KEPAHIANG','id_provinsi'=>17],
            ['id'=>1709,'kota'=>'KABUPATEN BENGKULU TENGAH','id_provinsi'=>17],
            ['id'=>1771,'kota'=>'KOTA BENGKULU','id_provinsi'=>17],
            ['id'=>1801,'kota'=>'KABUPATEN LAMPUNG BARAT','id_provinsi'=>18],
            ['id'=>1802,'kota'=>'KABUPATEN TANGGAMUS','id_provinsi'=>18],
            ['id'=>1803,'kota'=>'KABUPATEN LAMPUNG SELATAN','id_provinsi'=>18],
            ['id'=>1804,'kota'=>'KABUPATEN LAMPUNG TIMUR','id_provinsi'=>18],
            ['id'=>1805,'kota'=>'KABUPATEN LAMPUNG TENGAH','id_provinsi'=>18],
            ['id'=>1806,'kota'=>'KABUPATEN LAMPUNG UTARA','id_provinsi'=>18],
            ['id'=>1807,'kota'=>'KABUPATEN WAY KANAN','id_provinsi'=>18],
            ['id'=>1808,'kota'=>'KABUPATEN TULANGBAWANG','id_provinsi'=>18],
            ['id'=>1809,'kota'=>'KABUPATEN PESAWARAN','id_provinsi'=>18],
            ['id'=>1810,'kota'=>'KABUPATEN PRINGSEWU','id_provinsi'=>18],
            ['id'=>1811,'kota'=>'KABUPATEN MESUJI','id_provinsi'=>18],
            ['id'=>1812,'kota'=>'KABUPATEN TULANG BAWANG BARAT','id_provinsi'=>18],
            ['id'=>1813,'kota'=>'KABUPATEN PESISIR BARAT','id_provinsi'=>18],
            ['id'=>1871,'kota'=>'KOTA BANDAR LAMPUNG','id_provinsi'=>18],
            ['id'=>1872,'kota'=>'KOTA METRO','id_provinsi'=>18],
            ['id'=>1901,'kota'=>'KABUPATEN BANGKA','id_provinsi'=>19],
            ['id'=>1902,'kota'=>'KABUPATEN BELITUNG','id_provinsi'=>19],
            ['id'=>1903,'kota'=>'KABUPATEN BANGKA BARAT','id_provinsi'=>19],
            ['id'=>1904,'kota'=>'KABUPATEN BANGKA TENGAH','id_provinsi'=>19],
            ['id'=>1905,'kota'=>'KABUPATEN BANGKA SELATAN','id_provinsi'=>19],
            ['id'=>1906,'kota'=>'KABUPATEN BELITUNG TIMUR','id_provinsi'=>19],
            ['id'=>1971,'kota'=>'KOTA PANGKAL PINANG','id_provinsi'=>19],
            ['id'=>2101,'kota'=>'KABUPATEN KARIMUN','id_provinsi'=>21],
            ['id'=>2102,'kota'=>'KABUPATEN BINTAN','id_provinsi'=>21],
            ['id'=>2103,'kota'=>'KABUPATEN NATUNA','id_provinsi'=>21],
            ['id'=>2104,'kota'=>'KABUPATEN LINGGA','id_provinsi'=>21],
            ['id'=>2105,'kota'=>'KABUPATEN KEPULAUAN ANAMBAS','id_provinsi'=>21],
            ['id'=>2171,'kota'=>'KOTA BATAM','id_provinsi'=>21],
            ['id'=>2172,'kota'=>'KOTA TANJUNG PINANG','id_provinsi'=>21],
            ['id'=>3101,'kota'=>'KABUPATEN KEPULAUAN SERIBU','id_provinsi'=>31],
            ['id'=>3171,'kota'=>'KOTA JAKARTA SELATAN','id_provinsi'=>31],
            ['id'=>3172,'kota'=>'KOTA JAKARTA TIMUR','id_provinsi'=>31],
            ['id'=>3173,'kota'=>'KOTA JAKARTA PUSAT','id_provinsi'=>31],
            ['id'=>3174,'kota'=>'KOTA JAKARTA BARAT','id_provinsi'=>31],
            ['id'=>3175,'kota'=>'KOTA JAKARTA UTARA','id_provinsi'=>31],
            ['id'=>3201,'kota'=>'KABUPATEN BOGOR','id_provinsi'=>32],
            ['id'=>3202,'kota'=>'KABUPATEN SUKABUMI','id_provinsi'=>32],
            ['id'=>3203,'kota'=>'KABUPATEN CIANJUR','id_provinsi'=>32],
            ['id'=>3204,'kota'=>'KABUPATEN BANDUNG','id_provinsi'=>32],
            ['id'=>3205,'kota'=>'KABUPATEN GARUT','id_provinsi'=>32],
            ['id'=>3206,'kota'=>'KABUPATEN TASIKMALAYA','id_provinsi'=>32],
            ['id'=>3207,'kota'=>'KABUPATEN CIAMIS','id_provinsi'=>32],
            ['id'=>3208,'kota'=>'KABUPATEN KUNINGAN','id_provinsi'=>32],
            ['id'=>3209,'kota'=>'KABUPATEN CIREBON','id_provinsi'=>32],
            ['id'=>3210,'kota'=>'KABUPATEN MAJALENGKA','id_provinsi'=>32],
            ['id'=>3211,'kota'=>'KABUPATEN SUMEDANG','id_provinsi'=>32],
            ['id'=>3212,'kota'=>'KABUPATEN INDRAMAYU','id_provinsi'=>32],
            ['id'=>3213,'kota'=>'KABUPATEN SUBANG','id_provinsi'=>32],
            ['id'=>3214,'kota'=>'KABUPATEN PURWAKARTA','id_provinsi'=>32],
            ['id'=>3215,'kota'=>'KABUPATEN KARAWANG','id_provinsi'=>32],
            ['id'=>3216,'kota'=>'KABUPATEN BEKASI','id_provinsi'=>32],
            ['id'=>3217,'kota'=>'KABUPATEN BANDUNG BARAT','id_provinsi'=>32],
            ['id'=>3218,'kota'=>'KABUPATEN PANGANDARAN','id_provinsi'=>32],
            ['id'=>3271,'kota'=>'KOTA BOGOR','id_provinsi'=>32],
            ['id'=>3272,'kota'=>'KOTA SUKABUMI','id_provinsi'=>32],
            ['id'=>3273,'kota'=>'KOTA BANDUNG','id_provinsi'=>32],
            ['id'=>3274,'kota'=>'KOTA CIREBON','id_provinsi'=>32],
            ['id'=>3275,'kota'=>'KOTA BEKASI','id_provinsi'=>32],
            ['id'=>3276,'kota'=>'KOTA DEPOK','id_provinsi'=>32],
            ['id'=>3277,'kota'=>'KOTA CIMAHI','id_provinsi'=>32],
            ['id'=>3278,'kota'=>'KOTA TASIKMALAYA','id_provinsi'=>32],
            ['id'=>3279,'kota'=>'KOTA BANJAR','id_provinsi'=>32],
            ['id'=>3301,'kota'=>'KABUPATEN CILACAP','id_provinsi'=>33],
            ['id'=>3302,'kota'=>'KABUPATEN BANYUMAS','id_provinsi'=>33],
            ['id'=>3303,'kota'=>'KABUPATEN PURBALINGGA','id_provinsi'=>33],
            ['id'=>3304,'kota'=>'KABUPATEN BANJARNEGARA','id_provinsi'=>33],
            ['id'=>3305,'kota'=>'KABUPATEN KEBUMEN','id_provinsi'=>33],
            ['id'=>3306,'kota'=>'KABUPATEN PURWOREJO','id_provinsi'=>33],
            ['id'=>3307,'kota'=>'KABUPATEN WONOSOBO','id_provinsi'=>33],
            ['id'=>3308,'kota'=>'KABUPATEN MAGELANG','id_provinsi'=>33],
            ['id'=>3309,'kota'=>'KABUPATEN BOYOLALI','id_provinsi'=>33],
            ['id'=>3310,'kota'=>'KABUPATEN KLATEN','id_provinsi'=>33],
            ['id'=>3311,'kota'=>'KABUPATEN SUKOHARJO','id_provinsi'=>33],
            ['id'=>3312,'kota'=>'KABUPATEN WONOGIRI','id_provinsi'=>33],
            ['id'=>3313,'kota'=>'KABUPATEN KARANGANYAR','id_provinsi'=>33],
            ['id'=>3314,'kota'=>'KABUPATEN SRAGEN','id_provinsi'=>33],
            ['id'=>3315,'kota'=>'KABUPATEN GROBOGAN','id_provinsi'=>33],
            ['id'=>3316,'kota'=>'KABUPATEN BLORA','id_provinsi'=>33],
            ['id'=>3317,'kota'=>'KABUPATEN REMBANG','id_provinsi'=>33],
            ['id'=>3318,'kota'=>'KABUPATEN PATI','id_provinsi'=>33],
            ['id'=>3319,'kota'=>'KABUPATEN KUDUS','id_provinsi'=>33],
            ['id'=>3320,'kota'=>'KABUPATEN JEPARA','id_provinsi'=>33],
            ['id'=>3321,'kota'=>'KABUPATEN DEMAK','id_provinsi'=>33],
            ['id'=>3322,'kota'=>'KABUPATEN SEMARANG','id_provinsi'=>33],
            ['id'=>3323,'kota'=>'KABUPATEN TEMANGGUNG','id_provinsi'=>33],
            ['id'=>3324,'kota'=>'KABUPATEN KENDAL','id_provinsi'=>33],
            ['id'=>3325,'kota'=>'KABUPATEN BATANG','id_provinsi'=>33],
            ['id'=>3326,'kota'=>'KABUPATEN PEKALONGAN','id_provinsi'=>33],
            ['id'=>3327,'kota'=>'KABUPATEN PEMALANG','id_provinsi'=>33],
            ['id'=>3328,'kota'=>'KABUPATEN TEGAL','id_provinsi'=>33],
            ['id'=>3329,'kota'=>'KABUPATEN BREBES','id_provinsi'=>33],
            ['id'=>3371,'kota'=>'KOTA MAGELANG','id_provinsi'=>33],
            ['id'=>3372,'kota'=>'KOTA SURAKARTA','id_provinsi'=>33],
            ['id'=>3373,'kota'=>'KOTA SALATIGA','id_provinsi'=>33],
            ['id'=>3374,'kota'=>'KOTA SEMARANG','id_provinsi'=>33],
            ['id'=>3375,'kota'=>'KOTA PEKALONGAN','id_provinsi'=>33],
            ['id'=>3376,'kota'=>'KOTA TEGAL','id_provinsi'=>33],
            ['id'=>3401,'kota'=>'KABUPATEN KULON PROGO','id_provinsi'=>34],
            ['id'=>3402,'kota'=>'KABUPATEN BANTUL','id_provinsi'=>34],
            ['id'=>3403,'kota'=>'KABUPATEN GUNUNG KIDUL','id_provinsi'=>34],
            ['id'=>3404,'kota'=>'KABUPATEN SLEMAN','id_provinsi'=>34],
            ['id'=>3471,'kota'=>'KOTA YOGYAKARTA','id_provinsi'=>34],
            ['id'=>3501,'kota'=>'KABUPATEN PACITAN','id_provinsi'=>35],
            ['id'=>3502,'kota'=>'KABUPATEN PONOROGO','id_provinsi'=>35],
            ['id'=>3503,'kota'=>'KABUPATEN TRENGGALEK','id_provinsi'=>35],
            ['id'=>3504,'kota'=>'KABUPATEN TULUNGAGUNG','id_provinsi'=>35],
            ['id'=>3505,'kota'=>'KABUPATEN BLITAR','id_provinsi'=>35],
            ['id'=>3506,'kota'=>'KABUPATEN KEDIRI','id_provinsi'=>35],
            ['id'=>3507,'kota'=>'KABUPATEN MALANG','id_provinsi'=>35],
            ['id'=>3508,'kota'=>'KABUPATEN LUMAJANG','id_provinsi'=>35],
            ['id'=>3509,'kota'=>'KABUPATEN JEMBER','id_provinsi'=>35],
            ['id'=>3510,'kota'=>'KABUPATEN BANYUWANGI','id_provinsi'=>35],
            ['id'=>3511,'kota'=>'KABUPATEN BONDOWOSO','id_provinsi'=>35],
            ['id'=>3512,'kota'=>'KABUPATEN SITUBONDO','id_provinsi'=>35],
            ['id'=>3513,'kota'=>'KABUPATEN PROBOLINGGO','id_provinsi'=>35],
            ['id'=>3514,'kota'=>'KABUPATEN PASURUAN','id_provinsi'=>35],
            ['id'=>3515,'kota'=>'KABUPATEN SIDOARJO','id_provinsi'=>35],
            ['id'=>3516,'kota'=>'KABUPATEN MOJOKERTO','id_provinsi'=>35],
            ['id'=>3517,'kota'=>'KABUPATEN JOMBANG','id_provinsi'=>35],
            ['id'=>3518,'kota'=>'KABUPATEN NGANJUK','id_provinsi'=>35],
            ['id'=>3519,'kota'=>'KABUPATEN MADIUN','id_provinsi'=>35],
            ['id'=>3520,'kota'=>'KABUPATEN MAGETAN','id_provinsi'=>35],
            ['id'=>3521,'kota'=>'KABUPATEN NGAWI','id_provinsi'=>35],
            ['id'=>3522,'kota'=>'KABUPATEN BOJONEGORO','id_provinsi'=>35],
            ['id'=>3523,'kota'=>'KABUPATEN TUBAN','id_provinsi'=>35],
            ['id'=>3524,'kota'=>'KABUPATEN LAMONGAN','id_provinsi'=>35],
            ['id'=>3525,'kota'=>'KABUPATEN GRESIK','id_provinsi'=>35],
            ['id'=>3526,'kota'=>'KABUPATEN BANGKALAN','id_provinsi'=>35],
            ['id'=>3527,'kota'=>'KABUPATEN SAMPANG','id_provinsi'=>35],
            ['id'=>3528,'kota'=>'KABUPATEN PAMEKASAN','id_provinsi'=>35],
            ['id'=>3529,'kota'=>'KABUPATEN SUMENEP','id_provinsi'=>35],
            ['id'=>3571,'kota'=>'KOTA KEDIRI','id_provinsi'=>35],
            ['id'=>3572,'kota'=>'KOTA BLITAR','id_provinsi'=>35],
            ['id'=>3573,'kota'=>'KOTA MALANG','id_provinsi'=>35],
            ['id'=>3574,'kota'=>'KOTA PROBOLINGGO','id_provinsi'=>35],
            ['id'=>3575,'kota'=>'KOTA PASURUAN','id_provinsi'=>35],
            ['id'=>3576,'kota'=>'KOTA MOJOKERTO','id_provinsi'=>35],
            ['id'=>3577,'kota'=>'KOTA MADIUN','id_provinsi'=>35],
            ['id'=>3578,'kota'=>'KOTA SURABAYA','id_provinsi'=>35],
            ['id'=>3579,'kota'=>'KOTA BATU','id_provinsi'=>35],
            ['id'=>3601,'kota'=>'KABUPATEN PANDEGLANG','id_provinsi'=>36],
            ['id'=>3602,'kota'=>'KABUPATEN LEBAK','id_provinsi'=>36],
            ['id'=>3603,'kota'=>'KABUPATEN TANGERANG','id_provinsi'=>36],
            ['id'=>3604,'kota'=>'KABUPATEN SERANG','id_provinsi'=>36],
            ['id'=>3671,'kota'=>'KOTA TANGERANG','id_provinsi'=>36],
            ['id'=>3672,'kota'=>'KOTA CILEGON','id_provinsi'=>36],
            ['id'=>3673,'kota'=>'KOTA SERANG','id_provinsi'=>36],
            ['id'=>3674,'kota'=>'KOTA TANGERANG SELATAN','id_provinsi'=>36],
            ['id'=>5101,'kota'=>'KABUPATEN JEMBRANA','id_provinsi'=>51],
            ['id'=>5102,'kota'=>'KABUPATEN TABANAN','id_provinsi'=>51],
            ['id'=>5103,'kota'=>'KABUPATEN BADUNG','id_provinsi'=>51],
            ['id'=>5104,'kota'=>'KABUPATEN GIANYAR','id_provinsi'=>51],
            ['id'=>5105,'kota'=>'KABUPATEN KLUNGKUNG','id_provinsi'=>51],
            ['id'=>5106,'kota'=>'KABUPATEN BANGLI','id_provinsi'=>51],
            ['id'=>5107,'kota'=>'KABUPATEN KARANG ASEM','id_provinsi'=>51],
            ['id'=>5108,'kota'=>'KABUPATEN BULELENG','id_provinsi'=>51],
            ['id'=>5171,'kota'=>'KOTA DENPASAR','id_provinsi'=>51],
            ['id'=>5201,'kota'=>'KABUPATEN LOMBOK BARAT','id_provinsi'=>52],
            ['id'=>5202,'kota'=>'KABUPATEN LOMBOK TENGAH','id_provinsi'=>52],
            ['id'=>5203,'kota'=>'KABUPATEN LOMBOK TIMUR','id_provinsi'=>52],
            ['id'=>5204,'kota'=>'KABUPATEN SUMBAWA','id_provinsi'=>52],
            ['id'=>5205,'kota'=>'KABUPATEN DOMPU','id_provinsi'=>52],
            ['id'=>5206,'kota'=>'KABUPATEN BIMA','id_provinsi'=>52],
            ['id'=>5207,'kota'=>'KABUPATEN SUMBAWA BARAT','id_provinsi'=>52],
            ['id'=>5208,'kota'=>'KABUPATEN LOMBOK UTARA','id_provinsi'=>52],
            ['id'=>5271,'kota'=>'KOTA MATARAM','id_provinsi'=>52],
            ['id'=>5272,'kota'=>'KOTA BIMA','id_provinsi'=>52],
            ['id'=>5301,'kota'=>'KABUPATEN SUMBA BARAT','id_provinsi'=>53],
            ['id'=>5302,'kota'=>'KABUPATEN SUMBA TIMUR','id_provinsi'=>53],
            ['id'=>5303,'kota'=>'KABUPATEN KUPANG','id_provinsi'=>53],
            ['id'=>5304,'kota'=>'KABUPATEN TIMOR TENGAH SELATAN','id_provinsi'=>53],
            ['id'=>5305,'kota'=>'KABUPATEN TIMOR TENGAH UTARA','id_provinsi'=>53],
            ['id'=>5306,'kota'=>'KABUPATEN BELU','id_provinsi'=>53],
            ['id'=>5307,'kota'=>'KABUPATEN ALOR','id_provinsi'=>53],
            ['id'=>5308,'kota'=>'KABUPATEN LEMBATA','id_provinsi'=>53],
            ['id'=>5309,'kota'=>'KABUPATEN FLORES TIMUR','id_provinsi'=>53],
            ['id'=>5310,'kota'=>'KABUPATEN SIKKA','id_provinsi'=>53],
            ['id'=>5311,'kota'=>'KABUPATEN ENDE','id_provinsi'=>53],
            ['id'=>5312,'kota'=>'KABUPATEN NGADA','id_provinsi'=>53],
            ['id'=>5313,'kota'=>'KABUPATEN MANGGARAI','id_provinsi'=>53],
            ['id'=>5314,'kota'=>'KABUPATEN ROTE NDAO','id_provinsi'=>53],
            ['id'=>5315,'kota'=>'KABUPATEN MANGGARAI BARAT','id_provinsi'=>53],
            ['id'=>5316,'kota'=>'KABUPATEN SUMBA TENGAH','id_provinsi'=>53],
            ['id'=>5317,'kota'=>'KABUPATEN SUMBA BARAT DAYA','id_provinsi'=>53],
            ['id'=>5318,'kota'=>'KABUPATEN NAGEKEO','id_provinsi'=>53],
            ['id'=>5319,'kota'=>'KABUPATEN MANGGARAI TIMUR','id_provinsi'=>53],
            ['id'=>5320,'kota'=>'KABUPATEN SABU RAIJUA','id_provinsi'=>53],
            ['id'=>5321,'kota'=>'KABUPATEN MALAKA','id_provinsi'=>53],
            ['id'=>5371,'kota'=>'KOTA KUPANG','id_provinsi'=>53],
            ['id'=>6101,'kota'=>'KABUPATEN SAMBAS','id_provinsi'=>61],
            ['id'=>6102,'kota'=>'KABUPATEN BENGKAYANG','id_provinsi'=>61],
            ['id'=>6103,'kota'=>'KABUPATEN LANDAK','id_provinsi'=>61],
            ['id'=>6104,'kota'=>'KABUPATEN MEMPAWAH','id_provinsi'=>61],
            ['id'=>6105,'kota'=>'KABUPATEN SANGGAU','id_provinsi'=>61],
            ['id'=>6106,'kota'=>'KABUPATEN KETAPANG','id_provinsi'=>61],
            ['id'=>6107,'kota'=>'KABUPATEN SINTANG','id_provinsi'=>61],
            ['id'=>6108,'kota'=>'KABUPATEN KAPUAS HULU','id_provinsi'=>61],
            ['id'=>6109,'kota'=>'KABUPATEN SEKADAU','id_provinsi'=>61],
            ['id'=>6110,'kota'=>'KABUPATEN MELAWI','id_provinsi'=>61],
            ['id'=>6111,'kota'=>'KABUPATEN KAYONG UTARA','id_provinsi'=>61],
            ['id'=>6112,'kota'=>'KABUPATEN KUBU RAYA','id_provinsi'=>61],
            ['id'=>6171,'kota'=>'KOTA PONTIANAK','id_provinsi'=>61],
            ['id'=>6172,'kota'=>'KOTA SINGKAWANG','id_provinsi'=>61],
            ['id'=>6201,'kota'=>'KABUPATEN KOTAWARINGIN BARAT','id_provinsi'=>62],
            ['id'=>6202,'kota'=>'KABUPATEN KOTAWARINGIN TIMUR','id_provinsi'=>62],
            ['id'=>6203,'kota'=>'KABUPATEN KAPUAS','id_provinsi'=>62],
            ['id'=>6204,'kota'=>'KABUPATEN BARITO SELATAN','id_provinsi'=>62],
            ['id'=>6205,'kota'=>'KABUPATEN BARITO UTARA','id_provinsi'=>62],
            ['id'=>6206,'kota'=>'KABUPATEN SUKAMARA','id_provinsi'=>62],
            ['id'=>6207,'kota'=>'KABUPATEN LAMANDAU','id_provinsi'=>62],
            ['id'=>6208,'kota'=>'KABUPATEN SERUYAN','id_provinsi'=>62],
            ['id'=>6209,'kota'=>'KABUPATEN KATINGAN','id_provinsi'=>62],
            ['id'=>6210,'kota'=>'KABUPATEN PULANG PISAU','id_provinsi'=>62],
            ['id'=>6211,'kota'=>'KABUPATEN GUNUNG MAS','id_provinsi'=>62],
            ['id'=>6212,'kota'=>'KABUPATEN BARITO TIMUR','id_provinsi'=>62],
            ['id'=>6213,'kota'=>'KABUPATEN MURUNG RAYA','id_provinsi'=>62],
            ['id'=>6271,'kota'=>'KOTA PALANGKA RAYA','id_provinsi'=>62],
            ['id'=>6301,'kota'=>'KABUPATEN TANAH LAUT','id_provinsi'=>63],
            ['id'=>6302,'kota'=>'KABUPATEN KOTA BARU','id_provinsi'=>63],
            ['id'=>6303,'kota'=>'KABUPATEN BANJAR','id_provinsi'=>63],
            ['id'=>6304,'kota'=>'KABUPATEN BARITO KUALA','id_provinsi'=>63],
            ['id'=>6305,'kota'=>'KABUPATEN TAPIN','id_provinsi'=>63],
            ['id'=>6306,'kota'=>'KABUPATEN HULU SUNGAI SELATAN','id_provinsi'=>63],
            ['id'=>6307,'kota'=>'KABUPATEN HULU SUNGAI TENGAH','id_provinsi'=>63],
            ['id'=>6308,'kota'=>'KABUPATEN HULU SUNGAI UTARA','id_provinsi'=>63],
            ['id'=>6309,'kota'=>'KABUPATEN TABALONG','id_provinsi'=>63],
            ['id'=>6310,'kota'=>'KABUPATEN TANAH BUMBU','id_provinsi'=>63],
            ['id'=>6311,'kota'=>'KABUPATEN BALANGAN','id_provinsi'=>63],
            ['id'=>6371,'kota'=>'KOTA BANJARMASIN','id_provinsi'=>63],
            ['id'=>6372,'kota'=>'KOTA BANJAR BARU','id_provinsi'=>63],
            ['id'=>6401,'kota'=>'KABUPATEN PASER','id_provinsi'=>64],
            ['id'=>6402,'kota'=>'KABUPATEN KUTAI BARAT','id_provinsi'=>64],
            ['id'=>6403,'kota'=>'KABUPATEN KUTAI KARTANEGARA','id_provinsi'=>64],
            ['id'=>6404,'kota'=>'KABUPATEN KUTAI TIMUR','id_provinsi'=>64],
            ['id'=>6405,'kota'=>'KABUPATEN BERAU','id_provinsi'=>64],
            ['id'=>6409,'kota'=>'KABUPATEN PENAJAM PASER UTARA','id_provinsi'=>64],
            ['id'=>6411,'kota'=>'KABUPATEN MAHAKAM HULU','id_provinsi'=>64],
            ['id'=>6471,'kota'=>'KOTA BALIKPAPAN','id_provinsi'=>64],
            ['id'=>6472,'kota'=>'KOTA SAMARINDA','id_provinsi'=>64],
            ['id'=>6474,'kota'=>'KOTA BONTANG','id_provinsi'=>64],
            ['id'=>6501,'kota'=>'KABUPATEN MALINAU','id_provinsi'=>65],
            ['id'=>6502,'kota'=>'KABUPATEN BULUNGAN','id_provinsi'=>65],
            ['id'=>6503,'kota'=>'KABUPATEN TANA TIDUNG','id_provinsi'=>65],
            ['id'=>6504,'kota'=>'KABUPATEN NUNUKAN','id_provinsi'=>65],
            ['id'=>6571,'kota'=>'KOTA TARAKAN','id_provinsi'=>65],
            ['id'=>7101,'kota'=>'KABUPATEN BOLAANG MONGONDOW','id_provinsi'=>71],
            ['id'=>7102,'kota'=>'KABUPATEN MINAHASA','id_provinsi'=>71],
            ['id'=>7103,'kota'=>'KABUPATEN KEPULAUAN SANGIHE','id_provinsi'=>71],
            ['id'=>7104,'kota'=>'KABUPATEN KEPULAUAN TALAUD','id_provinsi'=>71],
            ['id'=>7105,'kota'=>'KABUPATEN MINAHASA SELATAN','id_provinsi'=>71],
            ['id'=>7106,'kota'=>'KABUPATEN MINAHASA UTARA','id_provinsi'=>71],
            ['id'=>7107,'kota'=>'KABUPATEN BOLAANG MONGONDOW UTARA','id_provinsi'=>71],
            ['id'=>7108,'kota'=>'KABUPATEN SIAU TAGULANDANG BIARO','id_provinsi'=>71],
            ['id'=>7109,'kota'=>'KABUPATEN MINAHASA TENGGARA','id_provinsi'=>71],
            ['id'=>7110,'kota'=>'KABUPATEN BOLAANG MONGONDOW SELATAN','id_provinsi'=>71],
            ['id'=>7111,'kota'=>'KABUPATEN BOLAANG MONGONDOW TIMUR','id_provinsi'=>71],
            ['id'=>7171,'kota'=>'KOTA MANADO','id_provinsi'=>71],
            ['id'=>7172,'kota'=>'KOTA BITUNG','id_provinsi'=>71],
            ['id'=>7173,'kota'=>'KOTA TOMOHON','id_provinsi'=>71],
            ['id'=>7174,'kota'=>'KOTA KOTAMOBAGU','id_provinsi'=>71],
            ['id'=>7201,'kota'=>'KABUPATEN BANGGAI KEPULAUAN','id_provinsi'=>72],
            ['id'=>7202,'kota'=>'KABUPATEN BANGGAI','id_provinsi'=>72],
            ['id'=>7203,'kota'=>'KABUPATEN MOROWALI','id_provinsi'=>72],
            ['id'=>7204,'kota'=>'KABUPATEN POSO','id_provinsi'=>72],
            ['id'=>7205,'kota'=>'KABUPATEN DONGGALA','id_provinsi'=>72],
            ['id'=>7206,'kota'=>'KABUPATEN TOLI-TOLI','id_provinsi'=>72],
            ['id'=>7207,'kota'=>'KABUPATEN BUOL','id_provinsi'=>72],
            ['id'=>7208,'kota'=>'KABUPATEN PARIGI MOUTONG','id_provinsi'=>72],
            ['id'=>7209,'kota'=>'KABUPATEN TOJO UNA-UNA','id_provinsi'=>72],
            ['id'=>7210,'kota'=>'KABUPATEN SIGI','id_provinsi'=>72],
            ['id'=>7211,'kota'=>'KABUPATEN BANGGAI LAUT','id_provinsi'=>72],
            ['id'=>7212,'kota'=>'KABUPATEN MOROWALI UTARA','id_provinsi'=>72],
            ['id'=>7271,'kota'=>'KOTA PALU','id_provinsi'=>72],
            ['id'=>7301,'kota'=>'KABUPATEN KEPULAUAN SELAYAR','id_provinsi'=>73],
            ['id'=>7302,'kota'=>'KABUPATEN BULUKUMBA','id_provinsi'=>73],
            ['id'=>7303,'kota'=>'KABUPATEN BANTAENG','id_provinsi'=>73],
            ['id'=>7304,'kota'=>'KABUPATEN JENEPONTO','id_provinsi'=>73],
            ['id'=>7305,'kota'=>'KABUPATEN TAKALAR','id_provinsi'=>73],
            ['id'=>7306,'kota'=>'KABUPATEN GOWA','id_provinsi'=>73],
            ['id'=>7307,'kota'=>'KABUPATEN SINJAI','id_provinsi'=>73],
            ['id'=>7308,'kota'=>'KABUPATEN MAROS','id_provinsi'=>73],
            ['id'=>7309,'kota'=>'KABUPATEN PANGKAJENE DAN KEPULAUAN','id_provinsi'=>73],
            ['id'=>7310,'kota'=>'KABUPATEN BARRU','id_provinsi'=>73],
            ['id'=>7311,'kota'=>'KABUPATEN BONE','id_provinsi'=>73],
            ['id'=>7312,'kota'=>'KABUPATEN SOPPENG','id_provinsi'=>73],
            ['id'=>7313,'kota'=>'KABUPATEN WAJO','id_provinsi'=>73],
            ['id'=>7314,'kota'=>'KABUPATEN SIDENRENG RAPPANG','id_provinsi'=>73],
            ['id'=>7315,'kota'=>'KABUPATEN PINRANG','id_provinsi'=>73],
            ['id'=>7316,'kota'=>'KABUPATEN ENREKANG','id_provinsi'=>73],
            ['id'=>7317,'kota'=>'KABUPATEN LUWU','id_provinsi'=>73],
            ['id'=>7318,'kota'=>'KABUPATEN TANA TORAJA','id_provinsi'=>73],
            ['id'=>7322,'kota'=>'KABUPATEN LUWU UTARA','id_provinsi'=>73],
            ['id'=>7325,'kota'=>'KABUPATEN LUWU TIMUR','id_provinsi'=>73],
            ['id'=>7326,'kota'=>'KABUPATEN TORAJA UTARA','id_provinsi'=>73],
            ['id'=>7371,'kota'=>'KOTA MAKASSAR','id_provinsi'=>73],
            ['id'=>7372,'kota'=>'KOTA PAREPARE','id_provinsi'=>73],
            ['id'=>7373,'kota'=>'KOTA PALOPO','id_provinsi'=>73],
            ['id'=>7401,'kota'=>'KABUPATEN BUTON','id_provinsi'=>74],
            ['id'=>7402,'kota'=>'KABUPATEN MUNA','id_provinsi'=>74],
            ['id'=>7403,'kota'=>'KABUPATEN KONAWE','id_provinsi'=>74],
            ['id'=>7404,'kota'=>'KABUPATEN KOLAKA','id_provinsi'=>74],
            ['id'=>7405,'kota'=>'KABUPATEN KONAWE SELATAN','id_provinsi'=>74],
            ['id'=>7406,'kota'=>'KABUPATEN BOMBANA','id_provinsi'=>74],
            ['id'=>7407,'kota'=>'KABUPATEN WAKATOBI','id_provinsi'=>74],
            ['id'=>7408,'kota'=>'KABUPATEN KOLAKA UTARA','id_provinsi'=>74],
            ['id'=>7409,'kota'=>'KABUPATEN BUTON UTARA','id_provinsi'=>74],
            ['id'=>7410,'kota'=>'KABUPATEN KONAWE UTARA','id_provinsi'=>74],
            ['id'=>7411,'kota'=>'KABUPATEN KOLAKA TIMUR','id_provinsi'=>74],
            ['id'=>7412,'kota'=>'KABUPATEN KONAWE KEPULAUAN','id_provinsi'=>74],
            ['id'=>7413,'kota'=>'KABUPATEN MUNA BARAT','id_provinsi'=>74],
            ['id'=>7414,'kota'=>'KABUPATEN BUTON TENGAH','id_provinsi'=>74],
            ['id'=>7415,'kota'=>'KABUPATEN BUTON SELATAN','id_provinsi'=>74],
            ['id'=>7471,'kota'=>'KOTA KENDARI','id_provinsi'=>74],
            ['id'=>7472,'kota'=>'KOTA BAUBAU','id_provinsi'=>74],
            ['id'=>7501,'kota'=>'KABUPATEN BOALEMO','id_provinsi'=>75],
            ['id'=>7502,'kota'=>'KABUPATEN GORONTALO','id_provinsi'=>75],
            ['id'=>7503,'kota'=>'KABUPATEN POHUWATO','id_provinsi'=>75],
            ['id'=>7504,'kota'=>'KABUPATEN BONE BOLANGO','id_provinsi'=>75],
            ['id'=>7505,'kota'=>'KABUPATEN GORONTALO UTARA','id_provinsi'=>75],
            ['id'=>7571,'kota'=>'KOTA GORONTALO','id_provinsi'=>75],
            ['id'=>7601,'kota'=>'KABUPATEN MAJENE','id_provinsi'=>76],
            ['id'=>7602,'kota'=>'KABUPATEN POLEWALI MANDAR','id_provinsi'=>76],
            ['id'=>7603,'kota'=>'KABUPATEN MAMASA','id_provinsi'=>76],
            ['id'=>7604,'kota'=>'KABUPATEN MAMUJU','id_provinsi'=>76],
            ['id'=>7605,'kota'=>'KABUPATEN MAMUJU UTARA','id_provinsi'=>76],
            ['id'=>7606,'kota'=>'KABUPATEN MAMUJU TENGAH','id_provinsi'=>76],
            ['id'=>8101,'kota'=>'KABUPATEN MALUKU TENGGARA BARAT','id_provinsi'=>81],
            ['id'=>8102,'kota'=>'KABUPATEN MALUKU TENGGARA','id_provinsi'=>81],
            ['id'=>8103,'kota'=>'KABUPATEN MALUKU TENGAH','id_provinsi'=>81],
            ['id'=>8104,'kota'=>'KABUPATEN BURU','id_provinsi'=>81],
            ['id'=>8105,'kota'=>'KABUPATEN KEPULAUAN ARU','id_provinsi'=>81],
            ['id'=>8106,'kota'=>'KABUPATEN SERAM BAGIAN BARAT','id_provinsi'=>81],
            ['id'=>8107,'kota'=>'KABUPATEN SERAM BAGIAN TIMUR','id_provinsi'=>81],
            ['id'=>8108,'kota'=>'KABUPATEN MALUKU BARAT DAYA','id_provinsi'=>81],
            ['id'=>8109,'kota'=>'KABUPATEN BURU SELATAN','id_provinsi'=>81],
            ['id'=>8171,'kota'=>'KOTA AMBON','id_provinsi'=>81],
            ['id'=>8172,'kota'=>'KOTA TUAL','id_provinsi'=>81],
            ['id'=>8201,'kota'=>'KABUPATEN HALMAHERA BARAT','id_provinsi'=>82],
            ['id'=>8202,'kota'=>'KABUPATEN HALMAHERA TENGAH','id_provinsi'=>82],
            ['id'=>8203,'kota'=>'KABUPATEN KEPULAUAN SULA','id_provinsi'=>82],
            ['id'=>8204,'kota'=>'KABUPATEN HALMAHERA SELATAN','id_provinsi'=>82],
            ['id'=>8205,'kota'=>'KABUPATEN HALMAHERA UTARA','id_provinsi'=>82],
            ['id'=>8206,'kota'=>'KABUPATEN HALMAHERA TIMUR','id_provinsi'=>82],
            ['id'=>8207,'kota'=>'KABUPATEN PULAU MOROTAI','id_provinsi'=>82],
            ['id'=>8208,'kota'=>'KABUPATEN PULAU TALIABU','id_provinsi'=>82],
            ['id'=>8271,'kota'=>'KOTA TERNATE','id_provinsi'=>82],
            ['id'=>8272,'kota'=>'KOTA TIDORE KEPULAUAN','id_provinsi'=>82],
            ['id'=>9101,'kota'=>'KABUPATEN FAKFAK','id_provinsi'=>91],
            ['id'=>9102,'kota'=>'KABUPATEN KAIMANA','id_provinsi'=>91],
            ['id'=>9103,'kota'=>'KABUPATEN TELUK WONDAMA','id_provinsi'=>91],
            ['id'=>9104,'kota'=>'KABUPATEN TELUK BINTUNI','id_provinsi'=>91],
            ['id'=>9105,'kota'=>'KABUPATEN MANOKWARI','id_provinsi'=>91],
            ['id'=>9106,'kota'=>'KABUPATEN SORONG SELATAN','id_provinsi'=>91],
            ['id'=>9107,'kota'=>'KABUPATEN SORONG','id_provinsi'=>91],
            ['id'=>9108,'kota'=>'KABUPATEN RAJA AMPAT','id_provinsi'=>91],
            ['id'=>9109,'kota'=>'KABUPATEN TAMBRAUW','id_provinsi'=>91],
            ['id'=>9110,'kota'=>'KABUPATEN MAYBRAT','id_provinsi'=>91],
            ['id'=>9111,'kota'=>'KABUPATEN MANOKWARI SELATAN','id_provinsi'=>91],
            ['id'=>9112,'kota'=>'KABUPATEN PEGUNUNGAN ARFAK','id_provinsi'=>91],
            ['id'=>9171,'kota'=>'KOTA SORONG','id_provinsi'=>91],
            ['id'=>9401,'kota'=>'KABUPATEN MERAUKE','id_provinsi'=>94],
            ['id'=>9402,'kota'=>'KABUPATEN JAYAWIJAYA','id_provinsi'=>94],
            ['id'=>9403,'kota'=>'KABUPATEN JAYAPURA','id_provinsi'=>94],
            ['id'=>9404,'kota'=>'KABUPATEN NABIRE','id_provinsi'=>94],
            ['id'=>9408,'kota'=>'KABUPATEN KEPULAUAN YAPEN','id_provinsi'=>94],
            ['id'=>9409,'kota'=>'KABUPATEN BIAK NUMFOR','id_provinsi'=>94],
            ['id'=>9410,'kota'=>'KABUPATEN PANIAI','id_provinsi'=>94],
            ['id'=>9411,'kota'=>'KABUPATEN PUNCAK JAYA','id_provinsi'=>94],
            ['id'=>9412,'kota'=>'KABUPATEN MIMIKA','id_provinsi'=>94],
            ['id'=>9413,'kota'=>'KABUPATEN BOVEN DIGOEL','id_provinsi'=>94],
            ['id'=>9414,'kota'=>'KABUPATEN MAPPI','id_provinsi'=>94],
            ['id'=>9415,'kota'=>'KABUPATEN ASMAT','id_provinsi'=>94],
            ['id'=>9416,'kota'=>'KABUPATEN YAHUKIMO','id_provinsi'=>94],
            ['id'=>9417,'kota'=>'KABUPATEN PEGUNUNGAN BINTANG','id_provinsi'=>94],
            ['id'=>9418,'kota'=>'KABUPATEN TOLIKARA','id_provinsi'=>94],
            ['id'=>9419,'kota'=>'KABUPATEN SARMI','id_provinsi'=>94],
            ['id'=>9420,'kota'=>'KABUPATEN KEEROM','id_provinsi'=>94],
            ['id'=>9426,'kota'=>'KABUPATEN WAROPEN','id_provinsi'=>94],
            ['id'=>9427,'kota'=>'KABUPATEN SUPIORI','id_provinsi'=>94],
            ['id'=>9428,'kota'=>'KABUPATEN MAMBERAMO RAYA','id_provinsi'=>94],
            ['id'=>9429,'kota'=>'KABUPATEN NDUGA','id_provinsi'=>94],
            ['id'=>9430,'kota'=>'KABUPATEN LANNY JAYA','id_provinsi'=>94],
            ['id'=>9431,'kota'=>'KABUPATEN MAMBERAMO TENGAH','id_provinsi'=>94],
            ['id'=>9432,'kota'=>'KABUPATEN YALIMO','id_provinsi'=>94],
            ['id'=>9433,'kota'=>'KABUPATEN PUNCAK','id_provinsi'=>94],
            ['id'=>9434,'kota'=>'KABUPATEN DOGIYAI','id_provinsi'=>94],
            ['id'=>9435,'kota'=>'KABUPATEN INTAN JAYA','id_provinsi'=>94],
            ['id'=>9436,'kota'=>'KABUPATEN DEIYAI','id_provinsi'=>94],
            ['id'=>9471,'kota'=>'KOTA JAYAPURA','id_provinsi'=>94],
            ];
            DB::table('kotas')->insert($kota);
    }
}